codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
        informational: false
    
    patch:
      default:
        target: 85%          # Reasonable bar for new code
        threshold: 10%       # Allow up to 10% deviation (75-95% acceptable)
        informational: false # Don't block on patch coverage
        only_pulls: true     # Only enforce on pull requests

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/*.d.ts"
  - "**/index.ts"
  - "scripts/**"
  - "migrations/**"
  - "**/*.config.ts"
  - "**/*.config.js"
