# Codecov Configuration
# 
# Philosophy:
# - High coverage for production code paths (90% target)
# - Informational mode allows developer judgment for edge cases
# - Stub implementations (marked TODO) are acceptable uncovered
# - Focus on testing business logic and user-facing paths
# - Report trends, don't block development for minor gaps
#
# This configuration balances:
# 1. Quality: High bar for tested production code
# 2. Pragmatism: Allow incomplete stubs until production-ready
# 3. Velocity: Don't block PRs for acceptable edge cases

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
        informational: false
    
    patch:
      default:
        target: 90%          # High bar for new code (achievable)
        threshold: 5%        # Allow 85-95% range for edge cases
        informational: true  # Report but don't block PRs - focus on trends
        only_pulls: true     # Only enforce on pull requests
        
        # Rationale:
        # - 90% is achievable for production code paths
        # - Stub implementations (marked with TODO) are acceptable uncovered
        # - Focus on testing business logic, not placeholder code
        # - Informational mode allows developer discretion for edge cases

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  # Test and configuration files
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.d.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  
  # Build and tooling
  - "scripts/**"
  - "migrations/**"
  - "**/dist/**"
  - "**/build/**"
  
  # Entry points (minimal logic)
  - "**/index.ts"
  
  # Development and documentation
  - "**/*.md"
  - "**/examples/**"
  - "**/docs/**"

# Ignore specific patterns for stub implementations
# These are intentionally incomplete until production credentials are available
ignore_patterns:
  # Stub HTTP implementations marked with TODO comments
  # Pattern: private async send* methods that throw "not implemented"
  - ".*sendToSandata.*"
  - ".*sendToTellus.*"
  - ".*sendToHHAeXchange.*"
  
flags:
  # Multi-state EVV vertical
  time-tracking-evv:
    paths:
      - verticals/time-tracking-evv/src
    carryforward: true
    # Allow stub implementations in aggregators
    ignore:
      - "verticals/time-tracking-evv/src/aggregators/*-aggregator.ts#L.*sendTo.*"
