#!/bin/bash
# Commands to add Stripe and Resend secrets to GitHub
# Run these AFTER you get the test mode keys from Stripe dashboard

echo "════════════════════════════════════════════════════════════"
echo "Add Secrets for Preview Environment"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Get your Stripe TEST mode secret key from:"
echo "   https://dashboard.stripe.com/test/apikeys"
echo ""
echo "2. Run this command (replace YOUR_KEY with actual key):"
echo ""
echo "   gh secret set PREVIEW_STRIPE_SECRET_KEY --body \"sk_test_YOUR_KEY_HERE\""
echo ""
echo "════════════════════════════════════════════════════════════"
echo "3. Create webhook endpoint at:"
echo "   https://dashboard.stripe.com/test/webhooks"
echo ""
echo "   Endpoint URL: https://care-commons-git-preview-neighborhood-lab.vercel.app/api/webhooks/stripe"
echo ""
echo "4. Copy the webhook signing secret and run:"
echo ""
echo "   gh secret set PREVIEW_STRIPE_WEBHOOK_SECRET --body \"whsec_YOUR_SECRET_HERE\""
echo ""
echo "════════════════════════════════════════════════════════════"
echo "5. Get Resend API key from: https://resend.com/api-keys"
echo ""
echo "6. Run this command:"
echo ""
echo "   gh secret set RESEND_API_KEY --body \"re_YOUR_KEY_HERE\""
echo ""
echo "════════════════════════════════════════════════════════════"
echo "Production Secrets (for later, when deploying to main)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Use LIVE mode keys from: https://dashboard.stripe.com/apikeys"
echo ""
echo "   gh secret set STRIPE_SECRET_KEY --body \"sk_live_YOUR_KEY_HERE\""
echo "   gh secret set STRIPE_WEBHOOK_SECRET --body \"whsec_YOUR_SECRET_HERE\""
echo ""
echo "════════════════════════════════════════════════════════════"
echo "Verify all secrets were added:"
echo ""
echo "   gh secret list | grep -E \"(STRIPE|RESEND)\""
echo ""
echo "════════════════════════════════════════════════════════════"
